// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CollapseController from "./collapse_controller"
application.register("collapse", CollapseController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MotionController from "./motion_controller"
application.register("motion", MotionController)

import ThemePickerController from "./theme_picker_controller"
application.register("theme-picker", ThemePickerController)
