---
require:
- rubocop-factory_bot
- rubocop-performance
- rubocop-rails
- rubocop-rspec
- rubocop-rspec_rails

AllCops:
  NewCops: enable
  SuggestExtensions: true
  TargetRubyVersion: 3.3
  Exclude:
  - 'vendor/bundle/**/*'
  - 'vendor/gems/**/*'
  - 'db/migrate/**/*.rb'
  - '**/db/migrate/**/*.rb'
  - '**/db/schema.rb'

Layout/LineLength:
  Max: 150

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
