---
require:
- rubocop-performance
- rubocop-rails
- rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: true
  TargetRubyVersion: 3.3
  Exclude:
  - 'vendor/bundle/**/*'
  - 'vendor/gems/**/*'
  - 'db/migrate/**/*.rb'
  - '**/db/migrate/**/*.rb'
  - '**/db/schema.rb'

Style/StringLiterals:
  Enabled: false
