name: Resume Docker Image Build
on:
  push:
    branches:
    - master
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: "actions/checkout@v5"
    - name: Publish
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: jebentier/resume
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: resume
